### ISSUE TITLE
Nested federation

### ISSUE THREAD

**Issue by Briansbum** [aidan-/aws-cli-federator#2]
If an account is able to be further used to federate access into other accounts this should be recognised and made available to the user as an option.

I'm probably wrong but it doesn't look like this is currently the case?

**Comment by aidan-** [comment]
I'm not sure if I quite understand your use case.  Do you have a link to an AWS doc explaining the federation from one account to another?  I have only seen mention of federation from an outside authentication source to a single account (via SAML, ADSL, etc).

If you are talking about assuming a role in a different account from an account you have authenticated to using this tool, this can be done via the assume role command after you have done the initial authentication:

```
aws sts assume-role --role-arn <arn of role to assume> --role-session <session name to use>
```
