### ISSUE TITLE
Roles are returned out of order

### ISSUE THREAD

**Issue by d-lord** [aidan-/aws-cli-federator#4]
If you have multiple roles, the tool doesn't present them in one consistent order every time. When you want to choose a role, you have to hunt for it in the list, which scales poorly as the number of roles increases. (I'm on three, I think @colbyprior is up to eight now).

Should roles be sorted alphabetically so you can consistently choose one? Or perhaps the text input should accept a pattern, or a new command-line parameter to do the same?

**Comment by aidan-** [comment]
Closed as per #5
